//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCAEntities : DbContext
    {
        public GCAEntities()
            : base("name=GCAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_chaves> tb_chaves { get; set; }
        public virtual DbSet<tb_maquinas> tb_maquinas { get; set; }
        public virtual DbSet<tb_setores> tb_setores { get; set; }
        public virtual DbSet<tb_software> tb_software { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<tb_compatibilidadeSO> tb_compatibilidadeSO { get; set; }
        public virtual DbSet<tb_relacionar> tb_relacionar { get; set; }
        public virtual DbSet<tb_tecnologia> tb_tecnologia { get; set; }
        public virtual DbSet<tb_tipoLicenca> tb_tipoLicenca { get; set; }
    }
}
