//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Chaves
    {
        public int ID_ChaveAtivacao { get; set; }
        public string DataDeCompra { get; set; }
        public string TipoDeLicenca { get; set; }
        public string PrazoDeLicenca { get; set; }
        public Nullable<int> ID_Software { get; set; }
        public string Software { get; set; }
        public string ChaveDeAtivacao { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
