//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_chaves
    {
        public int id_chave { get; set; }
        public string chave { get; set; }
        public string dataDeCompra { get; set; }
        public Nullable<int> id_tipoLicenca { get; set; }
        public string prazoLicenca { get; set; }
        public Nullable<int> id_software { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
