//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compatibilidadeSO
    {
        public int id_compatibilidadeSO { get; set; }
        public string compatibilidadeSO { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
