//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_software
    {
        public int id_software { get; set; }
        public string nomeSoftware { get; set; }
        public string versao { get; set; }
        public string ano { get; set; }
        public string fabricante { get; set; }
        public Nullable<int> id_idioma { get; set; }
        public Nullable<int> id_tecnologia { get; set; }
        public Nullable<int> id_compatibilidadeSO { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
