//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public int ID_Usuario { get; set; }
        public string NomeUsuario { get; set; }
        public string FuncaoUsuario { get; set; }
        public string SetorUsuario { get; set; }
        public Nullable<int> ID_Setor { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
