//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public int id_usuario { get; set; }
        public string nomeUsuario { get; set; }
        public string funcaoUsuario { get; set; }
        public Nullable<int> id_setor { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
